import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin } from "vite";
import {
  loadControlUiTranslationMemory,
  materializeControlUiLocaleCatalog,
  mergeControlUiTranslationMaps,
} from "../../scripts/lib/control-ui-i18n-catalog.ts";
import { CONTROL_UI_LOCALE_ENTRIES } from "../../scripts/lib/control-ui-i18n-config.ts";
import { flattenTranslations } from "../../scripts/lib/control-ui-i18n-sync-plan.ts";
import { registerActivityEnglish } from "../src/i18n/locales/en-activity.ts";
import { registerSessionPlacementEnglish } from "../src/i18n/locales/en-session-placement.ts";
import { en } from "../src/i18n/locales/en.ts";

const localeModulePrefix = "virtual:openclaw-control-ui-locale/";
const resolvedLocaleModulePrefix = `\0${localeModulePrefix}`;
// Vitest rewrites new URL(relative, import.meta.url) to browser self.location.
const i18nAssetsDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../src/i18n/.i18n",
);
const locales = new Set(CONTROL_UI_LOCALE_ENTRIES.map(({ locale }) => locale));
const sourceCatalog = mergeControlUiTranslationMaps(
  en,
  registerActivityEnglish.catalog,
  registerSessionPlacementEnglish.catalog,
);

export function controlUiLocaleModulesPlugin(): Plugin {
  return {
    name: "control-ui-locale-modules",
    enforce: "pre",
    resolveId(id) {
      if (id.startsWith(localeModulePrefix) && locales.has(id.slice(localeModulePrefix.length))) {
        return `\0${id}`;
      }
      return null;
    },
    load(id) {
      if (!id.startsWith(resolvedLocaleModulePrefix)) {
        return null;
      }
      const locale = id.slice(resolvedLocaleModulePrefix.length);
      if (!locales.has(locale)) {
        return null;
      }
      const memoryPath = path.join(i18nAssetsDir, `${locale}.tm.jsonl`);
      this.addWatchFile(memoryPath);
      // When the .tm.jsonl file does not exist the locale has been registered in
      // a source PR but its translation memory has not yet been generated by the
      // control-ui-locale-refresh workflow (which only runs from main). Return an
      // empty catalog so tests pass during source-PR CI; the workflow will populate
      // the memory after merge. If the file exists but is empty/corrupt, throw to
      // flag an unexpected state. Fixes #130070.
      if (!existsSync(memoryPath)) {
        console.warn(
          `[control-ui-locales] ${locale} translation memory not yet generated (${memoryPath}); returning empty catalog. Run control-ui-locale-refresh after merge.`,
        );
        return `export default {};`;
      }
      const memory = loadControlUiTranslationMemory(memoryPath);
      if (memory.size === 0) {
        throw new Error(`Control UI ${locale} translation memory is missing or empty`);
      }
      const catalog = materializeControlUiLocaleCatalog(flattenTranslations(sourceCatalog), memory);
      return `export default ${JSON.stringify(catalog)};`;
    },
  };
}
